create_clock -name clk -period 5.0 [get_ports clk]
create_generated_clock -name clk_div -source [get_ports clk] -divide_by 2 [get_nets clk_div]
set_false_path -from [get_ports rst_n]
set_input_delay 0.5 -clock clk_div [get_ports d]
set_output_delay 0.5 -clock clk_div [get_ports q]
